spring.data.mongodb:
  host: localhost
  port: 27017
  database: al3
  username: 34jf1djxc193c
  password: Password123
  authentication-database: admin

# no need to be authenticated
al3-security:
  permissible-requests:
    - "/login/**"
    - "/registration/**"
    - "/images/**"
    - "/mp3/**"
    - "/js/**"
    - "/error/**"
    - "/auth-test/authentication-not-required"

logging.level:
  org:
    springframework:
      data.*.*: trace
      cache.*: trace