POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

###
POST http://localhost:8080/registration
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "confirmPassword": "password"
}

###
